name: DeleteDirectory_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.SFTP.DeleteDirectory/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.SFTP.DeleteDirectory
      prebuild_command: docker-compose -f ./Frends.SFTP.DeleteDirectory.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      