name: Frends.SFTP.DownloadFiles Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.SFTP.DownloadFiles/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.SFTP.DownloadFiles
      prebuild_command: cd Frends.SFTP.DownloadFiles.Tests && docker-compose up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
