name: Frends.SFTP.ReadFile Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.SFTP.ReadFile/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.SFTP.ReadFile
      prebuild_command: docker-compose -f ./Frends.SFTP.ReadFile.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      