name: Frends.SFTP.ReadFile Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.SFTP.ReadFile/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.SFTP.ReadFile
      prebuild_command: docker-compose -f ./Frends.SFTP.ReadFile.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
