name: Frends.SFTP.RenameFile Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.SFTP.RenameFile/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.SFTP.RenameFile
      prebuild_command: docker-compose -f ./Frends.SFTP.RenameFile.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
