name: Frends.SFTP.UploadFiles Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.SFTP.UploadFiles/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.SFTP.UploadFiles
      env_var_name_1: HiQ_OpsTestSftpServerAddress
      env_var_name_2: HiQ_OpsTestSftpServerUsername
      env_var_name_3: HiQ_OpsTestSftpServerPassword
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_OPSTESTSFTPSERVERADDRESS }}
      env_var_value_2: ${{ secrets.HIQ_OPSTESTSFTPSERVERUSERNAME }}
      env_var_value_3: ${{ secrets.HIQ_OPSTESTSFTPSERVERPASSWORD }}
