name: Frends.SFTP.UploadFiles Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.SFTP.UploadFiles/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.SFTP.UploadFiles
      prebuild_command: docker-compose -f ./Frends.SFTP.UploadFiles.Tests/ up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
